package raw

// generated by schematyper -- DO NOT EDIT

// Catalog Entry (Image Provider)
type CatalogEntry struct {
	FileConfig FileConfig `json:"file,omitempty" yaml:"file,omitempty"`
	HTTPConfig HTTPConfig `json:"http,omitempty" yaml:"http,omitempty"`
	Key        string     `json:"key"            yaml:"key"`
	Type       string     `json:"type"           yaml:"type"`
}

// Associated Catalog Entry
type CatalogItem struct {
	Key            string          `json:"key" yaml:"key"`
	TimeRange      TimeRange       `json:"time_range" yaml:"time_range"`
	ColorReduction *ColorReduction `json:"color_reduction,omitempty" yaml:"color_reduction,omitempty"`
}

type ColorReduction struct {
	Size     uint     `json:"size" yaml:"size"`
	Strength float32 `json:"strength" yaml:"strength"`
	Type     string  `json:"type" yaml:"type"`
}

type Criteria struct {
	Exclude Exclude `json:"exclude,omitempty" yaml:"exclude,omitempty"`
	Include Include `json:"include,omitempty" yaml:"include,omitempty"`
}

type Crop struct {
	Strategy string `json:"strategy,omitempty" yaml:"strategy,omitempty"`
}

// Displays to configure
type Display struct {
	APIVersion             string         `json:"api_version" yaml:"api_version"`
	AssociatedCatalogEntry []CatalogItem  `json:"catalog" yaml:"catalog"`
	ColorReduction         ColorReduction `json:"color_reduction,omitempty" yaml:"color_reduction,omitempty"`
	Crop                   Crop           `json:"crop,omitempty" yaml:"crop,omitempty"`
	DisplayModel           string         `json:"model" yaml:"model"`
	DisplayOrientation     string         `json:"orientation" yaml:"orientation"`
	Flip                   bool           `json:"flip,omitempty" yaml:"flip,omitempty"`
	ImageProcessors        []Filter       `json:"filters,omitempty" yaml:"filters,omitempty"`
	Key                    string         `json:"mac_address" yaml:"mac_address"`
	Name                   string         `json:"name" yaml:"name"`
	ShowTimestamp          bool           `json:"show_timestamp,omitempty" yaml:"show_timestamp,omitempty"`
	SleepDurationSeconds   int            `json:"sleep_duration" yaml:"sleep_duration"`
}

// file_criteria
type Exclude struct {
	Path      []ExcludePathItem      `json:"path" yaml:"path"`
	TimeRange []ExcludeTimeRangeItem `json:"time_range" yaml:"time_range"`
}

type ExcludePathItem = string

type ExcludeTimeRangeItem struct {
	From string `json:"from" yaml:"from"`
	Last string `json:"last" yaml:"last"`
	To   string `json:"to" yaml:"to"`
}

type FileConfig struct {
	Criteria   Criteria `json:"criteria" yaml:"criteria"`
	SrcPath    string   `json:"src_path" yaml:"src_path"`
	Hooks      FileHooks `json:"hooks,omitempty" yaml:"hooks,omitempty"`
}

type FileHooks struct {
	OnNewFile string `json:"on_new_file,omitempty" yaml:"on_new_file,omitempty"`
}

type Filter struct {
	Type string                 `json:"type" yaml:"type"`
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

type HTTPConfig struct {
	URL         string            `json:"url"                    yaml:"url"`
	Method      string            `json:"method,omitempty"       yaml:"method,omitempty"`
	ImageSource *ImageSource      `json:"image_source,omitempty" yaml:"image_source,omitempty"`
	Cache       HTTPCacheConfig   `json:"cache,omitempty"        yaml:"cache,omitempty"`
	TimeoutSec  int               `json:"timeout_sec,omitempty"  yaml:"timeout_sec,omitempty"`
	Headers     map[string]string `json:"headers,omitempty"      yaml:"headers,omitempty"`
}

type ImageSource struct {
	Catalogs    []string `json:"catalogs"             yaml:"catalogs"`
	Mode        string   `json:"mode,omitempty"       yaml:"mode,omitempty"`
	ImageID     uint     `json:"image_id,omitempty"   yaml:"image_id,omitempty"`
	Orientation string   `json:"orientation,omitempty" yaml:"orientation,omitempty"`
	Tags        []string `json:"tags,omitempty"       yaml:"tags,omitempty"`
}

type HTTPCacheConfig struct {
	Type       string `json:"type,omitempty"        yaml:"type,omitempty"`
	Depth      int    `json:"depth,omitempty"       yaml:"depth,omitempty"`
	EvictCount int    `json:"evict_count,omitempty" yaml:"evict_count,omitempty"`
}

// file_criteria
type Include struct {
	Path      []IncludePathItem      `json:"path" yaml:"path"`
	TimeRange []IncludeTimeRangeItem `json:"time_range" yaml:"time_range"`
}

type IncludePathItem = string

type IncludeTimeRangeItem struct {
	From string `json:"from" yaml:"from"`
	Last string `json:"last" yaml:"last"`
	To   string `json:"to" yaml:"to"`
}

type ColorbarConfig struct{}

// WiSP Service Configuration
type ServiceConfig struct {
	Catalog  []CatalogEntry `json:"catalog" yaml:"catalog"`
	Displays []Display      `json:"displays" yaml:"displays"`
}

type TimeRange struct {
	Cron string `json:"cron" yaml:"cron"`
}
