package raw

// generated by schematyper -- DO NOT EDIT

// Catalog Entry (Image Provider)
type CatalogEntry struct {
	FileConfig       FileConfig       `json:"file,omitempty"       yaml:"file,omitempty"`
	HTTPConfig       HTTPConfig       `json:"http,omitempty"       yaml:"http,omitempty"`
	Key              string           `json:"key"                  yaml:"key"`
	LuaConfig        LuaConfig        `json:"lua,omitempty"        yaml:"lua,omitempty"`
	PlaywrightConfig PlaywrightConfig `json:"playwright,omitempty" yaml:"playwright,omitempty"`
	Type             string           `json:"type"                 yaml:"type"`
}

// Associated Catalog Entry
type CatalogItem struct {
	Key       string    `json:"key" yaml:"key"`
	TimeRange TimeRange `json:"time_range" yaml:"time_range"`
}

type ColorReduction struct {
	Size     uint     `json:"size" yaml:"size"`
	Strength float32 `json:"strength" yaml:"strength"`
	Type     string  `json:"type" yaml:"type"`
}

type Criteria struct {
	Exclude Exclude `json:"exclude,omitempty" yaml:"exclude,omitempty"`
	Include Include `json:"include,omitempty" yaml:"include,omitempty"`
}

type Crop struct {
	Strategy string `json:"strategy,omitempty" yaml:"strategy,omitempty"`
}

// Displays to configure
type Display struct {
	APIVersion             string         `json:"api_version" yaml:"api_version"`
	AssociatedCatalogEntry []CatalogItem  `json:"catalog" yaml:"catalog"`
	ColorReduction         ColorReduction `json:"color_reduction,omitempty" yaml:"color_reduction,omitempty"`
	Crop                   Crop           `json:"crop,omitempty" yaml:"crop,omitempty"`
	DisplayModel           string         `json:"model" yaml:"model"`
	DisplayOrientation     string         `json:"orientation" yaml:"orientation"`
	Flip                   bool           `json:"flip,omitempty" yaml:"flip,omitempty"`
	ImageProcessors        []Filter       `json:"filters,omitempty" yaml:"filters,omitempty"`
	Key                    string         `json:"mac_address" yaml:"mac_address"`
	Name                   string         `json:"name" yaml:"name"`
	ShowTimestamp          bool           `json:"show_timestamp,omitempty" yaml:"show_timestamp,omitempty"`
	SleepDurationSeconds   int            `json:"sleep_duration" yaml:"sleep_duration"`
}

// file_criteria
type Exclude struct {
	Path      []ExcludePathItem      `json:"path" yaml:"path"`
	TimeRange []ExcludeTimeRangeItem `json:"time_range" yaml:"time_range"`
}

type ExcludePathItem = string

type ExcludeTimeRangeItem struct {
	From string `json:"from" yaml:"from"`
	Last string `json:"last" yaml:"last"`
	To   string `json:"to" yaml:"to"`
}

type FileConfig struct {
	Criteria   Criteria `json:"criteria" yaml:"criteria"`
	SrcPath    string   `json:"src_path" yaml:"src_path"`
	Hooks      FileHooks `json:"hooks,omitempty" yaml:"hooks,omitempty"`
}

type FileHooks struct {
	OnNewFile string `json:"on_new_file,omitempty" yaml:"on_new_file,omitempty"`
}

type Filter struct {
	Type string                 `json:"type" yaml:"type"`
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

type HTTPConfig struct {
	URL string `json:"url" yaml:"url"`
}

// file_criteria
type Include struct {
	Path      []IncludePathItem      `json:"path" yaml:"path"`
	TimeRange []IncludeTimeRangeItem `json:"time_range" yaml:"time_range"`
}

type IncludePathItem = string

type IncludeTimeRangeItem struct {
	From string `json:"from" yaml:"from"`
	Last string `json:"last" yaml:"last"`
	To   string `json:"to" yaml:"to"`
}

type LuaConfig struct {
	Script string `json:"script" yaml:"script"`
}

type PlaywrightConfig struct {
	Server string `json:"server" yaml:"server"`
	URL    string `json:"url" yaml:"url"`
}

type ColorbarConfig struct{}

// WiSP Service Configuration
type ServiceConfig struct {
	Catalog  []CatalogEntry `json:"catalog" yaml:"catalog"`
	Displays []Display      `json:"displays" yaml:"displays"`
}

type TimeRange struct {
	Cron string `json:"cron" yaml:"cron"`
}
